name: MoreFish
authors:
  - elsiff
  - Musician101
website: https://elsiff.me, musician101.github.io
version: ${version}
main: me.elsiff.morefish.MoreFish
api-version: '1.20'
softdepend: [ mcMMO, MusiBoard, ProtocolLib, Vault ]
commands:
  morefish:
    description: Main command for MoreFish.
    usage: /morefish
    aliases: [ mf, fish ]
permissions:
  morefish.admin:
    default: op
    description: Give user ability to control the fishing contest.
