name: MoreFish
version: @version@
main: io.musician101.morefish.spigot.SpigotMoreFish
api-version: '1.15'
softdepend: [Vault, Citizens, PlaceholderAPI, ProtocolLib, mcMMO, WorldGuard]
authors: [elsiff, Musician101]
website: https://elsiff.me https://github.com/musician101
permissions:
  morefish.admin:
    default: op
    description: Give user ability to control the fishing contest.
  morefish.help:
    default: true
    description: Player with this permission can use the help command.
  morefish.top:
    default: true
    description: Player with this permission can use /morefish top command.
  morefish.shop:
    default: op
    description: Player with this permission can use /morefish shop command.
